# This workflow will be executed when master is updated:
# it will run the configured tests and upload the results on vfc_ci_master.

name: "Verificarlo CI (master)"

on:
  # Triggers the workflow when master is updated
  push:
    branches: [ master ]

  workflow_dispatch:


jobs:
  run_verificarlo_tests:
    runs-on: ubuntu-latest
    container: verificarlo/verificarlo

    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0

      - name: Run tests
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          vfc_ci test -g -r

      - name: Commit test results
        run: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA")

          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git checkout vfc_ci_master
          mkdir -p vfcruns
          mv *.vfcrun.h5 vfcruns
          git add vfcruns/*
          git commit -m "[auto] New test results for commit ${git_hash}"
          git push

      - name: Upload raw results as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{github.sha}}.vfcraw
          path: ./*.vfcraw.h5